export const initialState = {
  showSetting: false,
  savedData: false,
  activeThemeKind: undefined,
  selectedNode: undefined,
  language: undefined,
  folderPath: undefined,
  setting: undefined,
  gotDependencyTreeData: false,
  assetsBaseURL: undefined,
  getDataStatus: undefined,
  dependencyTreeData: undefined,
  getDataFailed: undefined,
  focusOn: undefined,
  viewHash: undefined,
  commandSettingStatus: {},
};
