export const TYPE_CHANGE_GET_DATA_STATUS = "TYPE_CHANGE_GET_DATA_STATUS";
export const TYPE_SET_DEPENDENCIES_TREE_DATA =
  "TYPE_SET_DEPENDENCIES_TREE_DATA";
export const TYPE_SET_FOCUS_ON_NODE = "TYPE_SET_FOCUS_ON_NODE";
export const TYPE_SET_ASSET_BASE_URL = "TYPE_SET_ASSET_BASE_URL";
export const TYPE_SET_FOLDER_PATH = "TYPE_SET_FOLDER_PATH";
export const TYPE_GET_WEBVIEW_HASH = "TYPE_GET_WEBVIEW_HASH";
export const TYPE_GET_LANGUAGE = "TYPE_GET_LANGUAGE";
export const TYPE_GET_ACTIVE_THEME_KIND = "TYPE_GET_ACTIVE_THEME_KIND";
export const TYPE_SELECT_NODE = "TYPE_SELECT_NODE";
export const TYPE_CHANGE_SETTING_STATUS = "TYPE_CHANGE_SETTING_STATUS";
export const TYPE_GET_ENTRY_FILE = "TYPE_GET_ENTRY_FILE";
